
package com.ottl.soapclient;

import jakarta.jws.*;
import jakarta.xml.bind.annotation.*;
import jakarta.xml.ws.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NaradaApiServicePortType", targetNamespace = "http://services.api.ycs.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NaradaApiServicePortType {


    /**
     * 
     * @param naradaRequest
     * @return
     *     returns com.ottl.soapclient.NaradaResponse
     */
    @WebMethod(action = "urn:serviceCall")
    @WebResult(name = "naradaResponse", targetNamespace = "http://services.api.ycs.com")
    @RequestWrapper(localName = "serviceCall", targetNamespace = "http://services.api.ycs.com", className = "com.ottl.soapclient.ServiceCall")
    @ResponseWrapper(localName = "serviceCallResponse", targetNamespace = "http://services.api.ycs.com", className = "com.ottl.soapclient.ServiceCallResponse")
    public NaradaResponse serviceCall(
        @WebParam(name = "naradaRequest", targetNamespace = "http://services.api.ycs.com")
        NaradaRequest naradaRequest);

    /**
     * 
     * @param echoReq
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:echo")
    @WebResult(name = "echoResp", targetNamespace = "http://services.api.ycs.com")
    @RequestWrapper(localName = "echo", targetNamespace = "http://services.api.ycs.com", className = "com.ottl.soapclient.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://services.api.ycs.com", className = "com.ottl.soapclient.EchoResponse")
    public String echo(
        @WebParam(name = "echoReq", targetNamespace = "http://services.api.ycs.com")
        String echoReq);

}
